Initial intake
AusTINCANsProgrammingTeam/2021RobotCode pull request #14
Opened 2021-02-10 02:01 UTC by SivonP

Code contains commands and subsystem for the initial intake

2021-03-02 00:42 UTC, AndrewIverson requested changes

2021-03-02 00:42 UTC, AndrewIverson commented on src/main/java/frc/robot/Constants.java
> +    public static final double kIntakeMotorMaxSpeed = 1.0;
Rename this to kIntakeMotorRunPercentage as that is how we are using it.

2021-03-02 00:42 UTC, AndrewIverson commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  public void setIntakeExtended(boolean isExtended) {
rename isExtended to setExtended or something that doesn't imply if a check of some kind. isExtended makes me think we are checking if something is correct.

2021-03-02 01:03 UTC, azvanderpas requested changes

2021-03-02 01:03 UTC, azvanderpas commented on src/main/java/frc/robot/commands/IntakeExtendFrameCommand.java
> +public class IntakeExtendFrameCommand extends CommandBase {
To simplify things, it would be easier to instantiate a StartEndCommand in RobotContainer formatted like below
Then this whole class can be deleted
 
```
myButton.toggleWhenPressed(new StartEndCommand(mySubsystem::onMethod,
    mySubsystem::offMethod,
    mySubsystem));
```

2021-03-02 01:30 UTC, azvanderpas approved these changes

2021-03-10 00:32 UTC, AndrewIverson approved these changes

2021-03-10 00:32 UTC, merged